apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  namespace: custom-namespace
spec:
  containers:
  - image: 192.168.233.60/library/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
